import React, { useState, useRef, useEffect } from 'react';
import { PatientProfile, ChatMessage } from '../types';
import { Printer, Sparkles, Send, AlertTriangle, Phone, Mic, X, StopCircle } from 'lucide-react';

interface CarerPortalProps {
  profile: PatientProfile;
}

const CarerPortal: React.FC<CarerPortalProps> = ({ profile }) => {
  const [situation, setSituation] = useState('');
  const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [isListening, setIsListening] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, loading, isListening]);

  const handlePrint = () => {
    window.print();
  };

  const handleTroubleshoot = async () => {
    if (!situation.trim()) return;

    const userText = situation;
    setSituation(''); // Clear immediately
    setLoading(true);
    
    // Add user message
    const userMsg: ChatMessage = { role: 'user', text: userText };
    setMessages(prev => [...prev, userMsg]);

    // const advice = await generateAdvice(profile, userText);
    // Add AI message with consistent response
    const aiMsg: ChatMessage = {
      role: 'model',
      text: 'The feature is not completed yet',
      isError: false
    };
    setMessages(prev => [...prev, aiMsg]);
    setLoading(false);
  };

  // Visual demo of Speech-to-Text functionality
  const toggleListening = () => {
    if (isListening) {
      setIsListening(false);
    } else {
      setIsListening(true);
      // SIMULATION: Listen for 2.5 seconds, then populate text
      setTimeout(() => {
        setIsListening(false);
      }, 2500);
    }
  };

  const isProfileEmpty = !profile.name;

  return (
    <div className="max-w-3xl mx-auto p-4 flex flex-col h-[calc(100vh-100px)]">
      
      {/* Printable Area Wrapper (Hidden from screen) */}
      <div className="print-only hidden">
        <h1 className="text-3xl font-bold mb-4">Care Profile: {profile.name || "Patient"}</h1>
        <div className="border-b-2 border-black mb-4"></div>
        <div className="grid grid-cols-1 gap-4 text-black">
           <section>
             <h3 className="font-bold text-xl uppercase">Stage</h3>
             <p>{profile.stage === 'early' ? 'Early Stage' : profile.stage === 'late' ? 'Later Stage' : 'N/A'}</p>
           </section>
           <section>
             <h3 className="font-bold text-xl uppercase">Important Memories</h3>
             <p>{profile.memories || "N/A"}</p>
           </section>
           <section>
             <h3 className="font-bold text-xl uppercase">Comforts & Coping</h3>
             <p>{profile.comforts || "N/A"}</p>
           </section>
           <section>
             <h3 className="font-bold text-xl uppercase">Music & Likes</h3>
             <p>{profile.music || "N/A"}</p>
           </section>
           <section>
             <h3 className="font-bold text-xl uppercase">Dislikes & Triggers</h3>
             <p>{profile.dislikes || "N/A"}</p>
           </section>
           <section>
             <h3 className="font-bold text-xl uppercase">Communication Style</h3>
             <p>{profile.communication || "N/A"}</p>
           </section>
           <section>
             <h3 className="font-bold text-xl uppercase">Comforting Routines</h3>
             <p>{profile.routines || "N/A"}</p>
           </section>
           <section>
             <h3 className="font-bold text-xl uppercase">Wishes</h3>
             <p>{profile.wishes || "N/A"}</p>
           </section>
        </div>
        <div className="mt-8 text-sm text-gray-500 text-center">
            Generated by Cracking the Code
        </div>
      </div>

      {/* Screen Header */}
      <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4 no-print shrink-0">
        <div>
          <h1 className="text-2xl font-bold text-nhs-darkBlue flex items-center gap-2">
            <Sparkles className="text-nhs-warmYellow" />
            AI Support Assistant
          </h1>
          <p className="text-sm text-gray-600">
            Expert advice tailored to {profile.name ? profile.name + "'s" : "your"} profile.
          </p>
        </div>
        <button 
          onClick={handlePrint}
          className="flex items-center justify-center gap-2 px-4 py-2 bg-white border border-gray-200 text-nhs-blue font-semibold rounded-lg shadow-sm hover:bg-blue-50 transition-colors"
        >
          <Printer size={18} />
          <span className="hidden sm:inline">Export Profile</span>
          <span className="sm:hidden">Export</span>
        </button>
      </header>

      {/* Warning if no profile */}
      {isProfileEmpty && (
        <div className="bg-orange-50 border-l-4 border-orange-500 p-3 mb-4 rounded-r-lg no-print shrink-0">
          <div className="flex items-start gap-3">
            <AlertTriangle className="text-orange-600 mt-1" size={20} />
            <div>
              <p className="font-bold text-orange-800 text-sm">Profile incomplete</p>
              <p className="text-orange-700 text-xs">
                Visit "My Profile" to personalize this advice.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Chat Area */}
      <div className="flex-1 bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden flex flex-col no-print relative">
        
        {/* Messages List */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-slate-50">
          {messages.length === 0 && (
            <div className="h-full flex flex-col items-center justify-center text-center text-gray-400 p-6 opacity-60">
              <div className="bg-white p-4 rounded-full mb-4 shadow-sm">
                 <Phone size={40} className="text-nhs-blue" />
              </div>
              <p className="text-lg font-medium text-gray-600 mb-2">Tap the green button to speak</p>
              <p className="text-sm">Or type your situation below.</p>
              <div className="mt-6 text-sm italic max-w-xs">
                "Mom is asking to go home but she is already here."
              </div>
            </div>
          )}
          
          {messages.map((msg, idx) => (
            <div key={idx} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'} animate-in slide-in-from-bottom-2`}>
              <div 
                className={`max-w-[85%] p-4 rounded-2xl text-base whitespace-pre-line shadow-sm ${
                  msg.role === 'user' 
                    ? 'bg-nhs-blue text-white rounded-br-none' 
                    : msg.isError 
                      ? 'bg-red-50 text-red-800 border border-red-200 rounded-bl-none'
                      : 'bg-white text-gray-800 border border-gray-200 rounded-bl-none'
                }`}
              >
                {msg.text}
              </div>
            </div>
          ))}

          {loading && (
             <div className="flex justify-start">
               <div className="bg-white p-4 rounded-2xl rounded-bl-none border border-gray-200 shadow-sm flex items-center gap-2">
                  <div className="w-2 h-2 bg-nhs-blue rounded-full animate-bounce" style={{animationDelay: '0ms'}}></div>
                  <div className="w-2 h-2 bg-nhs-blue rounded-full animate-bounce" style={{animationDelay: '150ms'}}></div>
                  <div className="w-2 h-2 bg-nhs-blue rounded-full animate-bounce" style={{animationDelay: '300ms'}}></div>
               </div>
            </div>
          )}

          {isListening && (
             <div className="flex justify-end">
               <div className="bg-green-50 text-green-800 p-4 rounded-2xl rounded-br-none border border-green-200 shadow-sm flex items-center gap-3">
                  <div className="animate-pulse flex gap-1 h-4 items-center">
                    <div className="w-1 h-2 bg-green-600 rounded-full animate-[pulse_1s_ease-in-out_infinite]"></div>
                    <div className="w-1 h-4 bg-green-600 rounded-full animate-[pulse_1.2s_ease-in-out_infinite]"></div>
                    <div className="w-1 h-3 bg-green-600 rounded-full animate-[pulse_0.8s_ease-in-out_infinite]"></div>
                  </div>
                  <span className="font-bold">Listening...</span>
               </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-4 bg-white border-t border-gray-100 relative z-10">
          
          {/* Tactile Call Button - Centered above input */}
          <div className="flex justify-center -mt-12 mb-4">
             <button 
               onClick={toggleListening}
               className={`
                 w-20 h-20 rounded-full shadow-xl flex items-center justify-center border-4 border-white transition-all transform active:scale-95
                 ${isListening 
                   ? 'bg-red-500 text-white animate-pulse' 
                   : 'bg-nhs-green text-white hover:bg-green-600 hover:scale-105'
                 }
               `}
               aria-label={isListening ? "Stop listening" : "Start voice input"}
             >
               {isListening ? <StopCircle size={36} fill="currentColor" /> : <Phone size={36} fill="currentColor" />}
             </button>
          </div>

          <div className="relative">
            <input 
              type="text" 
              value={situation}
              onChange={(e) => setSituation(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleTroubleshoot()}
              placeholder="Type your situation here..."
              className="w-full pl-5 pr-12 py-4 border-2 border-gray-200 rounded-full focus:border-nhs-blue focus:ring-4 focus:ring-blue-50 outline-none transition-all text-lg"
              disabled={loading || isListening}
            />
            <button 
              onClick={handleTroubleshoot}
              disabled={!situation.trim() || loading || isListening}
              className="absolute right-2 top-2 bottom-2 aspect-square bg-nhs-blue text-white rounded-full hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors flex items-center justify-center"
            >
              <Send size={20} className="ml-0.5" />
            </button>
          </div>
          <div className="text-center mt-2">
             <span className="text-xs text-gray-400 font-medium uppercase tracking-wide">
               {isListening ? "Tap to cancel" : "Tap phone to speak"}
             </span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CarerPortal;